In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
w = torch.tensor(2.0, requires_grad = True) # weight = 2
b = torch.tensor(-1.0, requires_grad = True) # bias = -1

In [4]:
def forward(x): # ŷ = -1 + 2x
    y = w * x + b
    return y

In [7]:
x = torch.tensor([1.0])
yhat = forward(x)
yhat

tensor([1.], grad_fn=<AddBackward0>)

In [12]:
x = torch.tensor([[1.0], [2.0]])
yhat = forward(x)
yhat

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [13]:
from torch.nn import Linear

In [18]:
model = Linear(in_features = 1, out_features = 1)
yhat = model(x)
yhat

tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward0>)

In [19]:
torch.manual_seed(1)
model = Linear(in_features = 1, out_features = 1)
print(list(model.parameters()))

x = torch.tensor([0.0])
yhat = model(x)
yhat

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


tensor([-0.4414], grad_fn=<ViewBackward0>)

In [ ]:
x = torch.tensor([[1.0], [-1.0]])
yhat = model(x)
yhat

tensor([[ 0.0739],
        [-0.9566]], grad_fn=<AddmmBackward0>)

CUSTOM MODULES

In [21]:
import torch.nn as nn

In [24]:
class LR(nn.Module):
    def __init__(self, ipSize, opSize):
        super(LR, self).__init__()
        self.linear = nn.Linear(ipSize, opSize)

    def forward(self, x):
        out = self.linear(x)
        return out